name:                created-with-idea
version:             0.1.0.0
github:              "Github username here/created-with-idea"
license:             BSD3
author:              "Author name here"
maintainer:          "Author email here"
copyright:           "2018 Author name here"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            App category here

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Github username here/created-with-idea#readme>

dependencies:
  - base >= 4.7 && < 5
  - containers
  - pretty-simple
  - aeson

library:
  source-dirs: src

executables:
  created-with-idea-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - created-with-idea

tests:
  created-with-idea-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - created-with-idea
